package dsd.view.risk;

import dsd.model.risk.Session;
import dsd.controller.risk.PlaceArmyManager;
import dsd.model.risk.Player;

/**
 *
 * @author UNC Risk Game Model
 */
public class Place_army_Interface extends javax.swing.JFrame {

    Session sessionstart;
    Player playerstart;
    String control = "SI";
    /**
     * Creates new form Interfaz
     */

    /**
     * 
     * @param session 
     */
    public Place_army_Interface(Session session, Player player) {
        playerstart = player;
        sessionstart = session;
        initComponents();
        this.setLocationRelativeTo(null);
        Button_aux.setVisible(false);
        Button_aux.setEnabled(false);
    }
    
    public Place_army_Interface(Session session, Player player,String a) {
        control = a;
        playerstart = player;
        sessionstart = session;
        initComponents();
        this.setLocationRelativeTo(null);
        Territory.setModel((new javax.swing.DefaultComboBoxModel(PlaceArmyManager.Territoriesneutral(sessionstart))));
        Army_player.setText("");
        jLabel1.setText("SELECT THE TERRITORY NEUTRAL");
    }
    
    
    public javax.swing.JLabel getlabel(){
        return jLabel1;
    }
    
    public javax.swing.JLabel getarmies(){
        return Army_player;
    }
    
    public String getTerritory(){
        return (String)Territory.getSelectedItem();
    }
    
    public javax.swing.JComboBox getTerritories(){
        return Territory;
    }
    
    
    public boolean Control(){
        return "SI".equals(control);
    }
    
    
    public void change(){
        Button_aux.setVisible(true);
        Button_aux.setEnabled(true);
        Button_finish.setVisible(false);
        Button_finish.setEnabled(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Army_player = new javax.swing.JLabel();
        Button_finish = new javax.swing.JButton();
        Button_aux = new javax.swing.JButton();
        Territory = new javax.swing.JComboBox();
        Map = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Logo_Risk = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Army_player.setForeground(new java.awt.Color(255, 255, 255));
        Army_player.setText((PlaceArmyManager.armies(sessionstart)));
        getContentPane().add(Army_player, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 130, 20));

        Button_finish.setText("Finish");
        Button_finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_finishActionPerformed(evt);
            }
        });
        getContentPane().add(Button_finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 110, -1));

        Button_aux.setText("Finish");
        Button_aux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_auxActionPerformed(evt);
            }
        });
        getContentPane().add(Button_aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 110, -1));

        Territory.setModel((new javax.swing.DefaultComboBoxModel(PlaceArmyManager.Territories(sessionstart))));
        Territory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerritoryActionPerformed(evt);
            }
        });
        getContentPane().add(Territory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 220, -1));

        Map.setIcon((new javax.swing.ImageIcon(getClass().getResource(PlaceArmyManager.Map(sessionstart)))));
        getContentPane().add(Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 85, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECTS THE TERRITORY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 200, -1));

        Logo_Risk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RISK-LOGO_EMEA.png"))); // NOI18N
        getContentPane().add(Logo_Risk, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 210, 70));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-hd-wallpapers-20.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TerritoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerritoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TerritoryActionPerformed

    
    /**
     * 
     * @param evt 
     */
    private void Button_finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_finishActionPerformed
        String name_territory = (String)Territory.getSelectedItem();
        PlaceArmyManager.Button_Finish(sessionstart, this, name_territory,playerstart);
    }//GEN-LAST:event_Button_finishActionPerformed

    private void Button_auxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_auxActionPerformed
        // TODO add your handling code here:
        String name_territory = (String)Territory.getSelectedItem();
        PlaceArmyManager.Button_aux(sessionstart, this, name_territory,playerstart);
    }//GEN-LAST:event_Button_auxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Army_player;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Button_aux;
    private javax.swing.JButton Button_finish;
    private javax.swing.JLabel Logo_Risk;
    private javax.swing.JLabel Map;
    private javax.swing.JComboBox Territory;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
