/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import manager.AttackManager;
import riskgamemodel.Session;

/**
 *
 * @author andre
 */
public class Declare_attack_Interface extends javax.swing.JFrame {

    Session sessionstart;
    /**
     * Creates new form Interfaz
     */
    public Declare_attack_Interface(Session session) {
        sessionstart = session;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo_Risk = new javax.swing.JLabel();
        Territory_attacker = new javax.swing.JComboBox();
        Map = new javax.swing.JLabel();
        Territory_Defender = new javax.swing.JComboBox<>();
        Button_Roll_Dice = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo_Risk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RISK-LOGO_EMEA.png"))); // NOI18N
        getContentPane().add(Logo_Risk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        Territory_attacker.setModel((new javax.swing.DefaultComboBoxModel(AttackManager.Territories(sessionstart))));
        Territory_attacker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Territory_attackerActionPerformed(evt);
            }
        });
        getContentPane().add(Territory_attacker, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 190, -1));

        Map.setIcon(((new javax.swing.ImageIcon(getClass().getResource(AttackManager.Map(sessionstart)))))
        );
        getContentPane().add(Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 350, 220));

        Territory_Defender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----" }));
        Territory_Defender.setEnabled(false);
        getContentPane().add(Territory_Defender, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 190, -1));

        Button_Roll_Dice.setText("Roll Dice");
        Button_Roll_Dice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Roll_DiceActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Roll_Dice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 90, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-hd-wallpapers-20.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Territory_attackerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Territory_attackerActionPerformed
        Territory_Defender.setEnabled(true);
        Territory_Defender.setModel(new javax.swing.DefaultComboBoxModel<>(AttackManager.neighbours(sessionstart, (String)Territory_attacker.getSelectedItem())));
    }//GEN-LAST:event_Territory_attackerActionPerformed

    private void Button_Roll_DiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Roll_DiceActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_Button_Roll_DiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Button_Roll_Dice;
    private javax.swing.JLabel Logo_Risk;
    private javax.swing.JLabel Map;
    private javax.swing.JComboBox<String> Territory_Defender;
    private javax.swing.JComboBox Territory_attacker;
    // End of variables declaration//GEN-END:variables
}
