package View;

import Controller.AttackManager;
import riskgamemodel.Session;

/**
 *
 * @author UNC Risk Game Model
 */
public class Declare_attack_Interface extends javax.swing.JFrame {

    Session sessionstart;
    /**
     * Creates new form Interfaz
     */
    
    /**
     * 
     * @param session 
     */
    public Declare_attack_Interface(Session session) {
        sessionstart = session;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo_Risk = new javax.swing.JLabel();
        Territory_attacker = new javax.swing.JComboBox();
        Map = new javax.swing.JLabel();
        Territory_Defender = new javax.swing.JComboBox<>();
        Button_Roll_Dice = new javax.swing.JButton();
        Button_finish = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo_Risk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RISK-LOGO_EMEA.png"))); // NOI18N
        getContentPane().add(Logo_Risk, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 210, 80));

        Territory_attacker.setModel((new javax.swing.DefaultComboBoxModel(AttackManager.Territories(sessionstart))));
        Territory_attacker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Territory_attackerActionPerformed(evt);
            }
        });
        getContentPane().add(Territory_attacker, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 290, -1));

        Map.setIcon(((new javax.swing.ImageIcon(getClass().getResource(AttackManager.Map(sessionstart)))))
        );
        getContentPane().add(Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 85, -1, -1));

        Territory_Defender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----" }));
        Territory_Defender.setEnabled(false);
        getContentPane().add(Territory_Defender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 290, -1));

        Button_Roll_Dice.setText("Roll Dice");
        Button_Roll_Dice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Roll_DiceActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Roll_Dice, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 110, 30));

        Button_finish.setText("Finish");
        Button_finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_finishActionPerformed(evt);
            }
        });
        getContentPane().add(Button_finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 90, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-hd-wallpapers-20.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt 
     */
    private void Territory_attackerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Territory_attackerActionPerformed
        Territory_Defender.setEnabled(true);
        Territory_Defender.setModel(new javax.swing.DefaultComboBoxModel<>(AttackManager.neighbours(sessionstart, (String)Territory_attacker.getSelectedItem())));
    }//GEN-LAST:event_Territory_attackerActionPerformed

    /**
     * 
     * @param evt 
     */
    private void Button_Roll_DiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Roll_DiceActionPerformed
        String terrAt = (String)Territory_attacker.getSelectedItem();
        String terrdef = (String)Territory_Defender.getSelectedItem();
        AttackManager.button_RollDie(this, sessionstart, terrAt, terrdef);
    }//GEN-LAST:event_Button_Roll_DiceActionPerformed

    /**
     * 
     * @param evt 
     */
    private void Button_finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_finishActionPerformed
        AttackManager.button_Finish(this, sessionstart);
    }//GEN-LAST:event_Button_finishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Button_Roll_Dice;
    private javax.swing.JButton Button_finish;
    private javax.swing.JLabel Logo_Risk;
    private javax.swing.JLabel Map;
    private javax.swing.JComboBox<String> Territory_Defender;
    private javax.swing.JComboBox Territory_attacker;
    // End of variables declaration//GEN-END:variables
}
