/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;

/**
 *
 * @author andre
 */
public class Main_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Main_Interface() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo_Risk = new javax.swing.JLabel();
        Button_Attack = new javax.swing.JButton();
        Button_Move_Army = new javax.swing.JButton();
        Button_Pass_Turn = new javax.swing.JButton();
        Map = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo_Risk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RISK-LOGO_EMEA.png"))); // NOI18N
        getContentPane().add(Logo_Risk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        Button_Attack.setText("Attack");
        Button_Attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AttackActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Attack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 110, 30));

        Button_Move_Army.setText("Move Army");
        Button_Move_Army.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Move_ArmyActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Move_Army, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 130, 30));

        Button_Pass_Turn.setText("Pass Turn");
        Button_Pass_Turn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Pass_TurnActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Pass_Turn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 140, 30));

        Map.setIcon(Map());
        getContentPane().add(Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-hd-wallpapers-20.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_AttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AttackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_AttackActionPerformed

    private void Button_Move_ArmyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Move_ArmyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Move_ArmyActionPerformed

    private void Button_Pass_TurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Pass_TurnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Pass_TurnActionPerformed

     private Icon Map(){
        String name = "ameroki_pic2";
        
        return (new javax.swing.ImageIcon(getClass().getResource("/images/" + name + ".jpg")));
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Button_Attack;
    private javax.swing.JButton Button_Move_Army;
    private javax.swing.JButton Button_Pass_Turn;
    private javax.swing.JLabel Logo_Risk;
    private javax.swing.JLabel Map;
    // End of variables declaration//GEN-END:variables
}
