package View;

import riskgamemodel.Session;
import Controller.PlaceArmyManager;
import Controller.SelectscapitalManager;
import riskgamemodel.Player;

/**
 *
 * @author UNC Risk Game Model
 */
public class Selects_capital_Interface extends javax.swing.JFrame {

    Session sessionstart;
    Player playerstart;
    /**
     * Creates new form Interfaz
     */

    /**
     * 
     * @param session 
     */
    public Selects_capital_Interface(Session session, Player player) {
        playerstart = player;
        sessionstart = session;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_finish = new javax.swing.JButton();
        Territory = new javax.swing.JComboBox();
        Selectscapital = new javax.swing.JLabel();
        Map = new javax.swing.JLabel();
        Logo_Risk = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_finish.setText("Finish");
        Button_finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_finishActionPerformed(evt);
            }
        });
        getContentPane().add(Button_finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 130, -1));

        Territory.setModel((new javax.swing.DefaultComboBoxModel(SelectscapitalManager.Territories(sessionstart))));
        Territory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerritoryActionPerformed(evt);
            }
        });
        getContentPane().add(Territory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 300, -1));

        Selectscapital.setForeground(new java.awt.Color(255, 255, 255));
        Selectscapital.setText("Selects the capital\n");
        getContentPane().add(Selectscapital, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 160, -1));

        Map.setIcon((new javax.swing.ImageIcon(getClass().getResource(PlaceArmyManager.Map(sessionstart)))));
        getContentPane().add(Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 85, -1, -1));

        Logo_Risk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RISK-LOGO_EMEA.png"))); // NOI18N
        getContentPane().add(Logo_Risk, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 210, 70));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-hd-wallpapers-20.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TerritoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerritoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TerritoryActionPerformed

    
    /**
     * 
     * @param evt 
     */
    private void Button_finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_finishActionPerformed
        String name_territory = (String)Territory.getSelectedItem();
        SelectscapitalManager.Button_Finish(sessionstart, this, name_territory,playerstart);
    }//GEN-LAST:event_Button_finishActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Button_finish;
    private javax.swing.JLabel Logo_Risk;
    private javax.swing.JLabel Map;
    private javax.swing.JLabel Selectscapital;
    private javax.swing.JComboBox Territory;
    // End of variables declaration//GEN-END:variables
}
