/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.SelectscapitalManager;
import riskgamemodel.Player;
import riskgamemodel.Session;

/**
 *
 * @author Sebastian
 */
public class Selects_capital_Interface extends javax.swing.JFrame {

    Player playerstart;
    Session sessionstart;

    public Selects_capital_Interface(Session session, Player player) {
        playerstart = player;
        sessionstart = session;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo_Risk = new javax.swing.JLabel();
        map = new javax.swing.JLabel();
        Territory = new javax.swing.JComboBox<>();
        Button_finish = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo_Risk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RISK-LOGO_EMEA.png"))); // NOI18N
        getContentPane().add(Logo_Risk, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 210, 70));

        map.setIcon((new javax.swing.ImageIcon(getClass().getResource(SelectscapitalManager.Map(sessionstart)))));
        getContentPane().add(map, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 85, -1, -1));

        Territory.setModel((new javax.swing.DefaultComboBoxModel(SelectscapitalManager.Territories(sessionstart))));
        getContentPane().add(Territory, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 310, -1));

        Button_finish.setText("Finish");
        Button_finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_finishActionPerformed(evt);
            }
        });
        getContentPane().add(Button_finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 90, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selects the capital");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 524, 130, 20));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-hd-wallpapers-20.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_finishActionPerformed
        String name_territory = (String)Territory.getSelectedItem();
        SelectscapitalManager.Button_Finish(sessionstart, this, name_territory, playerstart);
    }//GEN-LAST:event_Button_finishActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Button_finish;
    private javax.swing.JLabel Logo_Risk;
    private javax.swing.JComboBox<String> Territory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel map;
    // End of variables declaration//GEN-END:variables
}
